//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmPulse.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FarmPulse.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Yield.
        /// </summary>
        internal static string ActualYield {
            get {
                return ResourceManager.GetString("ActualYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add crop yield.
        /// </summary>
        internal static string AddCropYield {
            get {
                return ResourceManager.GetString("AddCropYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air temperature.
        /// </summary>
        internal static string AirTemperature {
            get {
                return ResourceManager.GetString("AirTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area ton/ha.
        /// </summary>
        internal static string AreaTonHa {
            get {
                return ResourceManager.GetString("AreaTonHa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Images.
        /// </summary>
        internal static string AvailableImages {
            get {
                return ResourceManager.GetString("AvailableImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home Screen.
        /// </summary>
        internal static string BackToHomeScreen {
            get {
                return ResourceManager.GetString("BackToHomeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUY NOW.
        /// </summary>
        internal static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorophylle Index.
        /// </summary>
        internal static string ChlorophylleIndex {
            get {
                return ResourceManager.GetString("ChlorophylleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has been submitted /n sucessfully..
        /// </summary>
        internal static string ConfirmationTitle1 {
            get {
                return ResourceManager.GetString("ConfirmationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note: The insurance agent as soon as /n will get in touch within 5 business days..
        /// </summary>
        internal static string ConfirmationTitle2 {
            get {
                return ResourceManager.GetString("ConfirmationTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm phone number.
        /// </summary>
        internal static string ConfirmPhoneNumber {
            get {
                return ResourceManager.GetString("ConfirmPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotton.
        /// </summary>
        internal static string Cotton {
            get {
                return ResourceManager.GetString("Cotton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        internal static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Insurance.
        /// </summary>
        internal static string CropInsurance {
            get {
                return ResourceManager.GetString("CropInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Monitoring.
        /// </summary>
        internal static string CropMonitoring {
            get {
                return ResourceManager.GetString("CropMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop type.
        /// </summary>
        internal static string CropType {
            get {
                return ResourceManager.GetString("CropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop yield data.
        /// </summary>
        internal static string CropYieldData {
            get {
                return ResourceManager.GetString("CropYieldData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT WEATHER.
        /// </summary>
        internal static string CurrentlyWeather {
            get {
                return ResourceManager.GetString("CurrentlyWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description the claim.
        /// </summary>
        internal static string DescriptionClaim {
            get {
                return ResourceManager.GetString("DescriptionClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate rates.
        /// </summary>
        internal static string EstimateRate {
            get {
                return ResourceManager.GetString("EstimateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer field name.
        /// </summary>
        internal static string FarmerFieldName {
            get {
                return ResourceManager.GetString("FarmerFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer Name and Surname.
        /// </summary>
        internal static string FarmerNameAndSurname {
            get {
                return ResourceManager.GetString("FarmerNameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer Phone number.
        /// </summary>
        internal static string FarmerPhoneNumber {
            get {
                return ResourceManager.GetString("FarmerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find ID/Password.
        /// </summary>
        internal static string FindIdPassword {
            get {
                return ResourceManager.GetString("FindIdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        internal static string Forecast {
            get {
                return ResourceManager.GetString("Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph View.
        /// </summary>
        internal static string GraphView {
            get {
                return ResourceManager.GetString("GraphView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectars.
        /// </summary>
        internal static string Hectars {
            get {
                return ResourceManager.GetString("Hectars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        internal static string Hybrid {
            get {
                return ResourceManager.GetString("Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index insurance.
        /// </summary>
        internal static string IndexInsurance {
            get {
                return ResourceManager.GetString("IndexInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index mean value.
        /// </summary>
        internal static string IndexMeanValue {
            get {
                return ResourceManager.GetString("IndexMeanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Number.
        /// </summary>
        internal static string InsuranceNumber {
            get {
                return ResourceManager.GetString("InsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check insurance number or password..
        /// </summary>
        internal static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit?.
        /// </summary>
        internal static string LogOutMessage {
            get {
                return ResourceManager.GetString("LogOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an request.
        /// </summary>
        internal static string MakeRequest {
            get {
                return ResourceManager.GetString("MakeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map View.
        /// </summary>
        internal static string MapView {
            get {
                return ResourceManager.GetString("MapView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDVI Index.
        /// </summary>
        internal static string NDVIIndex {
            get {
                return ResourceManager.GetString("NDVIIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet..
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase an insurance.
        /// </summary>
        internal static string PurchaseInsurance {
            get {
                return ResourceManager.GetString("PurchaseInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain 3 h.
        /// </summary>
        internal static string Rain3h {
            get {
                return ResourceManager.GetString("Rain3h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain Today.
        /// </summary>
        internal static string RainToday {
            get {
                return ResourceManager.GetString("RainToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        internal static string Satellite {
            get {
                return ResourceManager.GetString("Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Next.
        /// </summary>
        internal static string SaveAndNext {
            get {
                return ResourceManager.GetString("SaveAndNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ID/Password.
        /// </summary>
        internal static string SaveIdPassword {
            get {
                return ResourceManager.GetString("SaveIdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the crop.
        /// </summary>
        internal static string SelectCrop {
            get {
                return ResourceManager.GetString("SelectCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the field.
        /// </summary>
        internal static string SelectField {
            get {
                return ResourceManager.GetString("SelectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select index.
        /// </summary>
        internal static string SelectIndex {
            get {
                return ResourceManager.GetString("SelectIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Submited History.
        /// </summary>
        internal static string ShowSubmitedHistory {
            get {
                return ResourceManager.GetString("ShowSubmitedHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow Yestarday.
        /// </summary>
        internal static string SnowYestarday {
            get {
                return ResourceManager.GetString("SnowYestarday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Claim.
        /// </summary>
        internal static string StartNewClaim {
            get {
                return ResourceManager.GetString("StartNewClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting Claim.
        /// </summary>
        internal static string SubmittingClaim {
            get {
                return ResourceManager.GetString("SubmittingClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your claim.
        /// </summary>
        internal static string SubmitYourClaim {
            get {
                return ResourceManager.GetString("SubmitYourClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrian.
        /// </summary>
        internal static string Terrian {
            get {
                return ResourceManager.GetString("Terrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Period.
        /// </summary>
        internal static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Information.
        /// </summary>
        internal static string WeatherInformation {
            get {
                return ResourceManager.GetString("WeatherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        internal static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        internal static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WUA/Village.
        /// </summary>
        internal static string WuaVillage {
            get {
                return ResourceManager.GetString("WuaVillage", resourceCulture);
            }
        }
    }
}
